### ISSUE TITLE
Project Restructure, interested to collaborate?

### ISSUE THREAD

**Issue by itsjamie** [DanielRuf/esdoc-next#2]
Hello!

I'm looking at doing some restructuring of ESDoc to support optional chaining from the new Typescript version 3.7.3, and that will involve using @babel/parser.  Given that you've already done the work of upgrading from Babel 6, to Babel 7, I've forked from your repo.

I was planning on doing some restructuring to a mono-repo using Lerna to manage the plugins.

Additionally, I plan to increase the Node engine support to v8, and remove the use of ES modules and internal usage and switch to a CommonJS style for modules.

If these sound like something you would be interested in, I'll submit a PR with these changes.

**Comment by DanielRuf** [comment]
Hi @itsjamie,

Thanks for bringing this up.
One step after another.

Node 8 should not be used anymore and will reach its EOL this month, see https://github.com/nodejs/Release/blob/master/README.md.

Not sure why you would want to go back to cjs modules in the package itself.

Sure, this sounds great and your PR is very welcome. But please let's make a clear roadmap and ship real improvements, not yakshaving / bikeshedding stuff only.

**Comment by itsjamie** [comment]
> Not sure why you would want to go back to cjs modules in the package itself.

The reason for this was to make debugging easier. Currently, with the Babel-ified modules, all the modules stack traces don't match up with source.

I tried to use the new experimental modules support and ran into issues with the way the plugin system works.

**Comment by DanielRuf** [comment]
sourcemaps where meant to be used for this ;-)

**Comment by itsjamie** [comment]
Thanks!

I'm going to be working on this, and I'll submit a PR when I'm done if it matches up with something you're interested in taking.

**Comment by itsjamie** [comment]
https://github.com/itsjamie/esdoc-next

I got this into a place where I got the support I need to support TypeScript feature (Optional Chaining). Let me know!

**Comment by DanielRuf** [comment]
It seems you thre away all the history and commits of the people who have worked on that in the past. That is not very cool tbh.

**Comment by DanielRuf** [comment]
It seems you threw away all the history and commits of the people who have worked on that in the past. That is not very cool tbh.

**Comment by itsjamie** [comment]
Lerna import didn’t function correctly when I made the first pass. Cross
dependencies were being imported for each package which wasn’t necessary.
If your happy with the changes then a greater effort could be made.
Otherwise I’m planning on pointing at the original commit it was forked
from to get original Git history.

The original question stands, would you like a PR with the changes? Are
they in a direction you would like?

**Comment by DanielRuf** [comment]
> Otherwise I’m planning on pointing at the original commit it was forked from to get original Git history.

Sorry but that's not how it works.

You can easily delte the files of the current / old repo, do the migration step and copy the new files over. Then there is still a history because Git will see moved files.

>  The original question stands, would you like a PR with the changes? Are they in a direction you would like?

Not possible without doing the step to keep the old history. You can not merge two totally different histories.

**Comment by itsjamie** [comment]
Thank you for your comments.

**Comment by itsjamie** [comment]
I've addressed your comment regarding history. It is now present. As it isn't a fork I can't submit a PR for your consideration.

**Comment by itsjamie** [comment]
The repo now contains the history of the https://github.com/esdoc/esdoc-plugins repo and the https://github.com/esdoc/esdoc repo.

These have been migrated respectively to be packages that are deployed via Lerna.

esdoc/esdoc-plugins were moved into `packages/*`.
esdoc/esdoc has been moved into `packages/esdoc-cli` and `packages/esdoc-core`.

**Comment by itsjamie** [comment]
If I've gone a direction you aren't interested in long-term don't worry about it. I simply needed something to enable the feature-set I needed, and wanted to make it simpler to deploy going forward since it won't be a focus for myself.

**Comment by DanielRuf** [comment]
Thanks for the effort but as there is nothing that can be merged I'll close this.
